name: dbtc Concurrent Job per Customer

on:
  workflow_dispatch:

jobs:
  trigger-dbtc-job:
    runs-on: ubuntu-latest
    env:
        DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
        DBT_CLOUD_ACCOUNT_ID: 43786
        JOB_ID: 503518
    strategy:
      matrix:
        customer-id: [1, 2, 3, 4, 5] # Replace with your customer IDs

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v2
      with:
        python-version: "3.9.x"

    - name: Install dbtc
      run: pip install dbtc

    - name: Generate payload for customer ${{ matrix.customer-id }}
      run: |
        echo "PAYLOAD=$(python -c 'import json; print(json.dumps({"cause": "Concurrent trigger", "steps_override": ["dbt run -s stg_tpch_orders+ --vars \\"{\\\"customer_id\\\": \\\"${{ matrix.customer-id }}\\\"}\\""]}))')" >> $GITHUB_ENV

    - name: Run dbtc command with generated payload
      run: |
        dbtc trigger-job --job-id 503518 --payload "$PAYLOAD"